name: Continuous Integration
on: [push]
jobs:
  test-unit:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
      - uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff  # v3
      - uses: moonrepo/setup-rust@ede6de059f8046a5e236c94046823e2af11ca670 # v1.2.2
        with:
            bins: cargo-nextest, cargo-insta@1.28.0
      - run: just test-unit
  test-integration:
    name: Integration test (& build all in dev-mode)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
      - uses: ./.github/actions/setup-nix-direnv-rust
      - run: just test-integration
  lint:
    name: Lint & Style Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
      - uses: ./.github/actions/setup-nix-direnv-rust
      - run: just lint
